set -g @catppuccin_flavour 'mocha'
set -g @catppuccin_status_modules_right "session date_time"
set -g @catppuccin_status_modules_left ""
set -g @catppuccin_date_time_text "%d-%m-%Y %H:%M:%S"
run-shell "$HOME/.config/tmux/plugins/tmux/catppuccin.tmux"
