#!/bin/env bash

dotfiles_project_bin="${HOME}/Dropbox/code/01.github/projects/dotfiles/bin/dotfiles"

if [ ! -f "$dotfiles_project_bin" ];then
    echo "the binary file: $dotfiles_project_bin"
    echo "doens't exists!"
    exit 1
fi

# this subshell is necessary to avoid return to the original directory ('cd -')
(
  cd "$(dirname "$dotfiles_project_bin")" || exit 1
  ./dotfiles "$1"
)