#!/bin/env bash

project_list=($(tmuxinator list | sed -n '2p' | sed 's/ \+/ /g'))

selected_project=$(printf "%s\n" "${project_list[@]}" | grep -v "generic" |
    fzf --header-first --header="Projects" --height=10%
)

# Verifica se um projeto foi selecionado
if [ -n "$selected_project" ]; then
    # Inicia o projeto selecionado
    tmuxinator start "$selected_project"
else
    echo "Nenhum projeto selecionado."
    exit 0
fi