---
- name: "1PASSWORD | Detect 1Password"
  ansible.builtin.command:
    cmd: which op
  changed_when: false
  failed_when: false
  register: op_installed

- name: "1PASSWORD | Register 1Password"
  ansible.builtin.set_fact:
    op_installed: "{{ op_installed.rc == 0 }}"
  when: op_installed.rc == 0