---

# CONFIGURE PACKAGE MANAGERS
#######################################################################################
# To enable auto pasting, we can emulate  ctrl v (pasting) shortcut.
# more info here: https://github.com/HyDE-Project/HyDE/discussions/137#discussioncomment-11952405
- name: "HYDE | Install some packages"
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: present
  loop:
    - wtype

- name: "HYDE | Install some AUR packages"
  ansible.builtin.shell: yay -S --needed --noconfirm {{ item }}
  loop:
    - visual-studio-code-bin


# CONFIGURE PACKAGE MANAGERS
#######################################################################################
- name: "HYDE | Remove yay installation folder"
  ansible.builtin.file:
   path: "{{ ansible_user_dir }}/Clone"
   state: absent

- name: "HYDE | Comment 'ILoveCandy' line if it exists"
  become: true
  ansible.builtin.lineinfile:
    path: /etc/pacman.conf
    regexp: '^ILoveCandy'
    line: '# ILoveCandy'
    backrefs: true

# CONFIGURE MONITORS
#######################################################################################
- name: "HYDE | Detect system: VM or Host"
  ansible.builtin.shell: systemd-detect-virt
  register: virt_type
  changed_when: false
  ignore_errors: yes

- name: "HYDE | Define monitor configuration"
  ansible.builtin.set_fact:
    monitor_config_file: "{{ 'monitors_vm.conf' if virt_type.stdout != 'none' else 'monitors_host.conf' }}"

- name: "HYDE | Create symbolic link for monitors file"
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: true
  loop:
    - { src: "{{ role_path }}/files/monitors_host.conf", dest: "{{ ansible_user_dir }}/.config/hypr/monitors_host.conf" }
    - { src: "{{ role_path }}/files/monitors_vm.conf", dest: "{{ ansible_user_dir }}/.config/hypr/monitors_vm.conf" }

- name: "HYDE | Copy the monitor file"
  ansible.builtin.template:
    src: "monitors.conf.j2"
    dest: "{{ ansible_user_dir }}/.config/hypr/monitors.conf"
    mode: "0644"

# CONFIGURE KEYBOARDS
#######################################################################################
- name: "HYDE | Create symbolic link for keyboards file"
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: true
  loop:
    - { src: "{{ role_path }}/files/keyboard-us.conf", dest: "{{ ansible_user_dir }}/.config/hypr/keyboard-us.conf" }
    - { src: "{{ role_path }}/files/keyboard-pt_br.conf", dest: "{{ ansible_user_dir }}/.config/hypr/keyboard-pt_br.conf" }

# CONFIGURE USER PREFERENCES
#######################################################################################
- name: "HYDE | Create symbolic link for user preferences"
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: true
  loop:
    - { src: "{{ role_path }}/files/userprefs.conf", dest: "{{ ansible_user_dir }}/.config/hypr/userprefs.conf" }
    - { src: "{{ role_path }}/files/windowrules.conf", dest: "{{ ansible_user_dir }}/.config/hypr/windowrules.conf" }
    - { src: "{{ role_path }}/files/hypridle.conf", dest: "{{ ansible_user_dir }}/.config/hypr/hypridle.conf" }
    - { src: "{{ role_path }}/files/kitty.conf", dest: "{{ ansible_user_dir }}/.config/kitty/kitty.conf" }
    - { src: "{{ role_path }}/files/.hyde.zshrc", dest: "{{ ansible_user_dir }}/.hyde.zshrc" }

# Change some environment variables
- name: "HYDE | uncomment '$EDITOR' line"
  ansible.builtin.lineinfile:
    path: "{{ ansible_user_dir }}/.config/hypr/hyde.conf"
    regexp: "{{ item.regex }}"
    line: "{{ item.line }}"
    backrefs: true
  loop:
    - {regex: '^#\s*\$EDITOR', line: '$EDITOR = code'}
    - {regex: '^#\s*\$BROWSER', line: '$BROWSER = google-chrome-stable'}

- name: "HYDE | Remove some fastfecth logos"
  ansible.builtin.file:
   path: "{{ ansible_user_dir }}/.config/fastfetch/logo/{{ item }}"
   state: absent
  loop:
    - "aisaka.icon"
    - "loli.icon"
    - "pochita.icon"
    - "geass.icon"

- name: "HYDE | Copy new fastfetch icons"
  become_user: yes
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0644'
  loop:
    - { src: "{{ role_path }}/files/fastfetch_icons/arch-sticker.icon", dest: "{{ ansible_user_dir }}/.config/fastfetch/logo/arch-sticker.icon" }