
# Available: everforest | catppuccin | gruvbox | nord
%hidden ACTIVE_THEME=everforest

%if "#{==:#{ACTIVE_THEME},everforest}"
source-file "$HOME/.config/tmux/themes/everforest.conf"
%elif "#{==:#{ACTIVE_THEME},catppuccin}"
source-file "$HOME/.config/tmux/themes/catppuccin.conf"
%elif "#{==:#{ACTIVE_THEME},gruvbox}"
source-file "$HOME/.config/tmux/themes/gruvbox.conf"
%elif "#{==:#{ACTIVE_THEME},nord}"
source-file "$HOME/.config/tmux/themes/nord.conf"
%endif
