
source-file $HOME/.config/tmux/general.conf
source-file $HOME/.config/tmux/keybindings.conf
source-file $HOME/.config/tmux/plugins.conf
source-file $HOME/.config/tmux/themes.conf

run "$HOME/.config/tmux/plugins/tpm/tpm"
