name: homelab-iac
root: ~/Dropbox/code/01.github/homelab/homelab-iac

windows:
  - code:
      layout: af1d,133x52,0,0[133x38,0,0,47,133x13,0,39,50]

      panes:
      - $EDITOR .
      - clear && figlet -k -c -t "Homelab IaC" 
  - git: lazygit
  - servers: sshs --config ~/.ssh/config
  - IA: claude
