---
- name: Terraform | {{ ansible_distribution }} | Add the HashiCorp GPG key.
  become: true
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    keyring: /usr/share/keyrings/hashicorp-archive-keyring.gpg
    state: present

- name: Terraform | {{ ansible_distribution }} | Add the official HashiCorp Linux repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present

- name: Terraform | {{ ansible_distribution }} | Install Terraform
  become: true
  apt:
    name: terraform
    state: present