---
- name: "System | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yaml"
  register: system_distribution_config
  no_log: true

- name: "System | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yaml"
  when: system_distribution_config.stat.exists
  no_log: true


- name: "1PASSWORD | Ensure that {{ ansible_user_dir }}/.config/1password/ssh exists"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ ansible_user_dir }}/.config"
    - "{{ ansible_user_dir }}/.config/1password"
    - "{{ ansible_user_dir }}/.config/1password/ssh"

- name: "1PASSWORD | Update file /usr/share/applications/1password.desktop"
  become: true
  ansible.builtin.copy:
    src: "{{ role_path }}/files/1password.desktop"
    dest: "/usr/share/applications"
    mode: '0755'
    remote_src: true
    force: true

- name: "1PASSWORD | Create symbolic link for 1password/ssh/agent.toml"
  # become: yes
  ansible.builtin.file:
    src: "{{ role_path }}/files/agent.toml"
    dest: "{{ ansible_user_dir }}/.config/1password/ssh/agent.toml"
    state: link
    force: yes