# █░█ █▀ █▀▀ █▀█   █▀█ █▀█ █▀▀ █▀▀ █▀
# █▄█ ▄█ ██▄ █▀▄   █▀▀ █▀▄ ██▄ █▀░ ▄█

# Monitor Configuration
source = ./monitors.conf

# Keyboard Configuration
source = ./keyboard-us.conf


# This flags are necessary to fix disappearing drop-down menu on Zoom
# See more:
# - https://forum.endeavouros.com/t/hyprland-how-i-fixed-disappearing-drop-down-menus/49095
# - https://www.reddit.com/r/hyprland/comments/1iv3xxc/zoom_menus_disappear_with_follow_mouse1/
follow_mouse=1
mouse_refocus=false

#TODO: Remover essa linha quando esse PR for mergeado na branch master: https://github.com/HyDE-Project/HyDE/pull/1614
bind = $mainMod, J, layoutmsg, togglesplit

# // █░░ ▄▀█ █░█ █▄░█ █▀▀ █░█
# // █▄▄ █▀█ █▄█ █░▀█ █▄▄ █▀█

exec-once = sleep 10 && dropbox start -i
exec-once = sleep 12 && insync start
exec-once = sleep 14 && env XDG_SESSION_TYPE=x11 1password --silent

