---
- name: "Kubecolor | Download Latest Version JSON"
  ansible.builtin.uri:
    url: https://api.github.com/repos/kubecolor/kubecolor/releases/latest
  register: kubecolor_latest_version_json
  changed_when: false

- name: "Kubecolor | Registering Kubecolor Latest Release"
  ansible.builtin.set_fact:
    kubecolor_latest_release: "{{ kubecolor_latest_version_json.json.tag_name | replace('v', '')}}"

- name: "Kubecolor | Download .deb package"
  ansible.builtin.get_url:
    url: "https://github.com/kubecolor/kubecolor/releases/download/v{{ kubecolor_latest_release }}/kubecolor_{{ kubecolor_latest_release }}_linux_amd64.tar.gz"
    dest: /tmp/kubecolor.tar.gz

- name: "Kubecolor | Extract tarball"
  become: true
  ansible.builtin.unarchive:
    src: /tmp/kubecolor.tar.gz
    dest: "/usr/local/bin"

- name: "Kubecolor | Cleanup downloaded tar"
  ansible.builtin.file:
    path: "/tmp/kubecolor.tar.gz"
    state: absent