---
- name: Cleanup k9s downloaded tar
  become: true
  ansible.builtin.file:
    path: "/tmp/{{ k9s_file }}.tar.gz"
    state: absent

- name: Remove extracted k9s directory
  become: true
  ansible.builtin.file:
    path: /tmp/k9s
    state: absent
