---
- name: "Kind | Download Kind binary"
  ansible.builtin.get_url:
    url: "https://kind.sigs.k8s.io/dl/{{ k8s.kind_version }}/kind-linux-amd64"
    dest: "/tmp/kind"
    mode: '0755'

- name: "Kind | Remove any current kind installations"
  become: true
  ansible.builtin.file:
    path: "/usr/local/bin/kind"
    state: absent

- name: "Kind | Move Kind to bin"
  become: true
  ansible.builtin.copy:
    src: "/tmp/kind"
    dest: "/usr/local/bin"
    mode: '0755'
    remote_src: true

- name: "Kind | Remove donwloaded binary"
  become: true
  ansible.builtin.file:
    path: "/tmp/kind"
    state: absent