---
- name: "INSYNC | install"
  ansible.builtin.shell: "yay -S --needed --noconfirm insync"

- name: "INSYNC | start service"
  become: true
  ansible.builtin.systemd:
    name: "insync@{{ host_user }}"
    state: started
    enabled: yes
    scope: system  # Para serviços do sistema (remova se for `--user`)