---
- name: "GO | Install dependencies"
  become: true
  apt:
    name: "{{ item }}"
    state: present
  loop:
      - 'curl'
      - 'gcc'
      - 'git'
      - 'findutils'
      - 'make'
      - 'rsync'
      - 'tar'
      - 'jq'
  register: apt_result
  until: apt_result is success
  retries: 1
  delay: 2

- name: "GO | Install"
  become: true
  ansible.builtin.apt:
    name: "golang"
    state: present
    update_cache: true