---
- name: "System | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yaml"
  register: system_distribution_config

- name: "System | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yaml"
  when: system_distribution_config.stat.exists

- name: Vim | link the config file
  ansible.builtin.file:
    src: "{{ role_path }}/files/.vimrc"
    dest: "{{ ansible_user_dir }}/.vimrc"
    state: link