---
- name: "System | Checking for Distribution Config: {{ ansible_facts.distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_facts.distribution }}.yaml"
  register: system_distribution_config
  no_log: true

- name: "System | Run Tasks: {{ ansible_facts.distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_facts.distribution }}.yaml"
  when: system_distribution_config.stat.exists
  no_log: true

- name: Vim | link the config file
  ansible.builtin.file:
    src: "{{ role_path }}/files/.vimrc"
    dest: "{{ ansible_facts.user_dir }}/.vimrc"
    state: link