name: dotfiles
root: ~/Dropbox/code/01.github/linux_ricing_project/dotfiles

windows:
  - code:
      layout: main-horizontal
      panes:
        - clear && figlet -k -c -t "Dotfiles" && onefetch && sleep 1 && code .
        - watch -n 5 incus list
  - docker:
    - lazydocker
  - git:
    - lazygit