---
- name: "System | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yaml"
  register: system_distribution_config

- name: "System | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yaml"
  when: system_distribution_config.stat.exists

# Linking Config file
- name: "ZSH | Ensure clean .zshrc file"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.zshrc"
    state: absent

- name: "ZSH | Create symbolic link for .zshrc"
  become: yes
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: "{{ role_path }}/files/.zshrc", dest: "{{ ansible_user_dir }}/.zshrc" }
    - { src: "{{ role_path }}/files/.p10k.zsh", dest: "{{ ansible_user_dir }}/.p10k.zsh" }

- name: "ZSH | Change to zsh"
  become: yes
  ansible.builtin.shell: chsh -s $(which zsh)