---
# Ubuntu Installation
########################################################################################
- name: "ZSH | Update APT package index"
  become: yes
  ansible.builtin.apt:
    update_cache: yes

- name: ZSH | Install Zsh
  become: yes
  ansible.builtin.apt:
    name: zsh
    state: present
    install_recommends: yes

- name: "ZSH | Create symbolic link for .zshrc"
  become: yes
  ansible.builtin.file:
    src: "{{ role_path }}/files/.zshrc"
    dest: "{{ ansible_env.HOME }}/.zshrc"
    state: link
  loop:
    - { src: "{{ role_path }}/files/.zshrc", dest: "{{ ansible_env.HOME }}/.zshrc" }
    - { src: "{{ role_path }}/files/.p10k.zsh", dest: "{{ ansible_env.HOME }}/.p10k.zsh" }

- name: "ZSH | Change to zsh"
  become: yes
  ansible.builtin.shell: chsh -s $(which zsh)