---
- name: "KUBECTL | Get latest kubectl version"
  ansible.builtin.uri:
    url: https://dl.k8s.io/release/stable.txt
    return_content: yes
  register: kubectl_version

- name: "KUBECTL | Set kubectl download URL"
  ansible.builtin.set_fact:
    kubectl_url: "https://dl.k8s.io/release/{{ kubectl_version.content | trim }}/bin/linux/amd64/kubectl"

- name: "KUBECTL | Download kubectl to /tmp"
  ansible.builtin.get_url:
    url: "{{ kubectl_url }}"
    dest: "/tmp/kubectl"
    mode: '0755'

- name: "KUBECTL | Ensure ~/.local/bin directory exists"
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/bin"
    state: directory
    mode: '0755'

- name: "KUBECTL | Move kubectl to ~/.local/bin"
  ansible.builtin.copy:
    src: "/tmp/kubectl"
    dest: "{{ ansible_env.HOME }}/.local/bin/kubectl"
    remote_src: yes
    mode: '0755'