---
- name: "Helm | Download Latest Version JSON"
  ansible.builtin.uri:
    url: https://api.github.com/repos/helm/helm/releases/latest
  register: helm_latest_version_json
  changed_when: false

- name: "Helm | Registering Helm Latest Release"
  ansible.builtin.set_fact:
    helm_latest_release: "{{ helm_latest_version_json.json.tag_name }}"

- name: "Helm | Download .deb package"
  ansible.builtin.get_url:
    url: "https://get.helm.sh/helm-{{ helm_latest_release }}-linux-amd64.tar.gz"
    dest: /tmp/helm.tar.gz

- name: "Helm | Extract tarball"
  ansible.builtin.unarchive:
    src: /tmp/helm.tar.gz
    dest: "/tmp"

- name: "Helm | Move Helm to /usr/local/bin"
  become: true
  copy:
    src: "/tmp/linux-amd64/helm"
    dest: "/usr/local/bin"
    mode: '0755'
    remote_src: true

- name: "Helm | Cleanup downloaded tar"
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/tmp/helm.tar.gz"
    - "/tmp/linux-amd64"