---
- name: "BAT | Install"
  become: yes
  ansible.builtin.apt:
    name: "bat"
    state: present

- name: "BAT | Get path of bat binary"
  ansible.builtin.command: "which batcat"
  register: bat_binary_path
  changed_when: false
  failed_when: bat_binary_path.rc != 0

- name: "BAT | Ensure ~/.local/bin exists"
  ansible.builtin.file:
    path: "{{ primary_installation_path }}"
    state: directory
    mode: '0755'

- name: "BAT | Create symlink to ~/.local/bin/bat"
  ansible.builtin.file:
    src: "{{ bat_binary_path.stdout }}"
    dest: "{{ primary_installation_path }}/bat"
    state: link
    force: true