---
- name: "DOCKER | Install docker, docker-compose, docker-buildx"
  become: true
  community.general.pacman:
    name:
      - docker
      - docker-compose
      - docker-buildx
    state: present

- name: "LAZYDOCKER | Install"
  ansible.builtin.shell: "curl https://raw.githubusercontent.com/jesseduffield/lazydocker/master/scripts/install_update_linux.sh | bash"
