---
- name: "System | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yaml"
  register: system_distribution_config
  no_log: true

- name: "System | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yaml"
  when: system_distribution_config.stat.exists
  no_log: true

- name: "Docker | Enable service"
  become: true
  ansible.builtin.systemd:
    enabled: true
    name: docker
    state: started

- name: "Docker | Add to group"
  become: true
  ansible.builtin.user:
    append: true
    groups: docker
    name: "{{ ansible_user_id }}"

- name: "Docker | Ensure docker data directory exists"
  become: true
  ansible.builtin.file:
    path: "{{  ansible_user_dir }}/.local/lib/docker"
    state: directory
    mode: "0710"