---
- name: "Dropbox | Download Dropbox tarball"
  ansible.builtin.get_url:
    url: "http://www.dropbox.com/download/?plat=lnx.x86_64"
    dest: /tmp/dropbox.tar.gz

- name: "Dropbox | Extract Dropbox tarball"
  ansible.builtin.unarchive:
    src: /tmp/dropbox.tar.gz
    dest: /tmp

- name: "Dropbox | Move Dropbox to /opt/dropbox"
  become: true
  copy:
    src: "/tmp/.dropbox-dist"
    dest: "/opt/dropbox"
    mode: '0755'
    remote_src: true

- name: "Dropbox | Create symbolic link for dropboxd"
  become: yes
  ansible.builtin.file:
    src: /opt/dropbox/.dropbox-dist/dropboxd
    dest: /usr/bin/dropbox
    state: link

- name: "Dropbox | Ensure ~/.config/autostart directory exists"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/autostart"
    state: directory
    mode: '0755'

- name: "Dropbox | Copy dropbox.desktop to /usr/share/applications"
  become: yes
  ansible.builtin.copy:
    src: "{{ role_path }}/files/dropbox.desktop"
    dest: /usr/share/applications/dropbox.desktop
    owner: root
    group: root
    mode: '0644'

- name: "Dropbox | Copy dropbox.desktop to ~/.config/autostart"
  ansible.builtin.copy:
    src: "{{ role_path }}/files/dropbox.desktop"
    dest: "{{ ansible_user_dir }}/.config/autostart/dropbox.desktop"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0644'